#!/usr/bin/env bash

tune() {

  case $1 in
      sil)
          [[ $(amixer get Master | grep "Mono:" ) =~ .*"[on]"*. ]] && \
          amixer sset Master mute || amixer sset Master unmute
          ;;

      up)
          amixer sset Master 5%+
          ;;
      down)
          amixer sset Master 5%-
          ;;
      *)
          amixer sset Master 30%
          ;;
  esac
}


tune $1
